// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChatMessage {
  final PlatformInt64 id;
  final String role;
  final String content;
  final String timestamp;

  const ChatMessage({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^ role.hashCode ^ content.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          role == other.role &&
          content == other.content &&
          timestamp == other.timestamp;
}

class MemoryItem {
  final PlatformInt64 id;
  final String content;
  final String createdAt;

  const MemoryItem({
    required this.id,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode => id.hashCode ^ content.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          createdAt == other.createdAt;
}

class ProfileTrait {
  final String category;
  final String content;

  const ProfileTrait({
    required this.category,
    required this.content,
  });

  @override
  int get hashCode => category.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileTrait &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          content == other.content;
}
