// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_model_path`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> sendMessage(
        {required String message,
        required double temperature,
        required int maxTokens}) =>
    RustLib.instance.api.crateApiSimpleSendMessage(
        message: message, temperature: temperature, maxTokens: maxTokens);

Future<List<ChatMessage>> getChatHistory() =>
    RustLib.instance.api.crateApiSimpleGetChatHistory();
