// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_init_error`, `prepare_message_context`, `resolve_model_path`, `set_init_error`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> sendMessage(
        {required String message,
        required double temperature,
        required int maxTokens}) =>
    RustLib.instance.api.crateApiSimpleSendMessage(
        message: message, temperature: temperature, maxTokens: maxTokens);

Stream<String> sendMessageStream(
        {required String message,
        required double temperature,
        required int maxTokens}) =>
    RustLib.instance.api.crateApiSimpleSendMessageStream(
        message: message, temperature: temperature, maxTokens: maxTokens);

Future<double> getTemperature() =>
    RustLib.instance.api.crateApiSimpleGetTemperature();

Future<bool> setTemperature({required double temperature}) =>
    RustLib.instance.api.crateApiSimpleSetTemperature(temperature: temperature);

Future<String> exportBrain() =>
    RustLib.instance.api.crateApiSimpleExportBrain();

Future<bool> saveAssistantMessage({required String message}) =>
    RustLib.instance.api.crateApiSimpleSaveAssistantMessage(message: message);

Future<String> generateProactiveGreeting({required String timeOfDay}) =>
    RustLib.instance.api
        .crateApiSimpleGenerateProactiveGreeting(timeOfDay: timeOfDay);

Future<List<ChatMessage>> getChatHistory() =>
    RustLib.instance.api.crateApiSimpleGetChatHistory();

Future<List<MemoryItem>> getAllMemories() =>
    RustLib.instance.api.crateApiSimpleGetAllMemories();

Future<bool> deleteMemory({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSimpleDeleteMemory(id: id);

Future<String> getCorePrompt() =>
    RustLib.instance.api.crateApiSimpleGetCorePrompt();

Future<bool> setCorePrompt({required String prompt}) =>
    RustLib.instance.api.crateApiSimpleSetCorePrompt(prompt: prompt);

Future<String> getUserName() =>
    RustLib.instance.api.crateApiSimpleGetUserName();

Future<bool> setUserName({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetUserName(name: name);

Future<String> getAppLanguage() =>
    RustLib.instance.api.crateApiSimpleGetAppLanguage();

Future<bool> setAppLanguage({required String lang}) =>
    RustLib.instance.api.crateApiSimpleSetAppLanguage(lang: lang);

Future<bool> addProfileTrait(
        {required String category, required String content}) =>
    RustLib.instance.api
        .crateApiSimpleAddProfileTrait(category: category, content: content);

Future<bool> exportDatabase({required String destPath}) =>
    RustLib.instance.api.crateApiSimpleExportDatabase(destPath: destPath);

Future<bool> factoryReset() =>
    RustLib.instance.api.crateApiSimpleFactoryReset();

Future<bool> runSleepCycle() =>
    RustLib.instance.api.crateApiSimpleRunSleepCycle();

Future<List<ProfileTrait>> getProfileTraits() =>
    RustLib.instance.api.crateApiSimpleGetProfileTraits();

Future<bool> clearProfile() =>
    RustLib.instance.api.crateApiSimpleClearProfile();

Future<void> initApp(
        {required String chatModelPath, required String embeddingModelPath}) =>
    RustLib.instance.api.crateApiSimpleInitApp(
        chatModelPath: chatModelPath, embeddingModelPath: embeddingModelPath);
