// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> saveUserMessage({required String content}) =>
    RustLib.instance.api.crateApiSaveUserMessage(content: content);

Future<List<EpisodicMemoryDto>> getRecentMemories({required int limit}) =>
    RustLib.instance.api.crateApiGetRecentMemories(limit: limit);

class EpisodicMemoryDto {
  final String id;
  final String timestamp;
  final String role;
  final String content;
  final bool processed;

  const EpisodicMemoryDto({
    required this.id,
    required this.timestamp,
    required this.role,
    required this.content,
    required this.processed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      timestamp.hashCode ^
      role.hashCode ^
      content.hashCode ^
      processed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodicMemoryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timestamp == other.timestamp &&
          role == other.role &&
          content == other.content &&
          processed == other.processed;
}
